Fixed. LoadError: cannot load such file -- bundler/dep_proxy
https://travis-ci.org/sue445/rubicure/jobs/348787632

```
bundler: failed to load command: rspec (/home/travis/build/sue445/rubicure/vendor/bundle/ruby/2.6.0/bin/rspec)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in
```

c.f. ttps://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443