Fix CI on activesupport 5.0
```
  1) Rubicure::Series#to_json
     Failure/Error: it { should eq json.squish }

     NoMethodError:
       undefined method `squish' for "{\"series_name\":\"splash_star\",\"title\":\"ふたりはプリキュア Splash☆Star\",\"started_date\":\"2006-02-05\",\"ended_date\":\"2007-01-28\",\"girls\":[\"cure_bloom\",\"cure_egret\"]}\n":String
     # ./spec/rubicure/series_spec.rb:161:in `block (3 levels) in <top (required)>'
```

https://github.com/sue445/rubicure/actions/runs/6419959150/job/17430972458#step:6:82